services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: restaurant_ordering
      DB_USER: root
      DB_PASSWORD: 123456
      DB_HOST: db
      DB_PORT: 3306

  db:
    environment:
      MYSQL_DATABASE: restaurant_ordering
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
