# Generated by Django 4.2.30 on 2026-08-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Platform Admin', 'Platform Admin'), ('owner', 'Owner'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
