# Generated by Django 4.2.30 on 2026-08-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Admin'), ('owner', 'Owner'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
