# Generated by Django 4.2.30 on 2026-08-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Admin'), ('owner', 'Owner'), ('waiter', 'Waiter'), ('chef', 'Chef')], default='waiter', max_length=20),
        ),
    ]
