# Generated by Django 4.2.30 on 2026-08-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('user', '0005_user_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='user',
            name='restaurant',
            field=models.ManyToManyField(blank=True, related_name='employees', to='restaurant.restaurant'),
        ),
    ]
