# Generated by Django 4.2.30 on 2026-08-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('user', '0006_remove_user_restaurant_user_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='user',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='restaurant.restaurant'),
        ),
    ]
