# Generated by Django 4.2.30 on 2026-08-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
